// src/devtools/subpanels/abi-playground.vue
<template lang="pug">
.abi-playground
  .playground-div

</template>

<script>
import { mapGetters } from 'vuex';
import React from 'react';
import ReactDOM from 'react-dom';
import ABIPlayGround from './abi-playground.jsx';

export default {
  data: () => ({
  }),
  computed: {
    ...mapGetters(['contracts']),
  },
  created() { },
  mounted() {
    console.log(ABIPlayGround);
    const playground = React.createElement(ABIPlayGround, { contracts: this.contracts }, null);
    console.log(playground);
    const playgroundDiv = document.getElementsByClassName('playground-div')[0];
    ReactDOM.render(playground, playgroundDiv);
  },
  methods: { },
};
</script>

<style lang="less">
.abi-playground {

}
</style>

// src/devtools/subpanels/abi-playground.jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import TestABI from './testABI.json';

import FullContract from './FullContract.jsx';

class ABIPlayGround extends Component {
  constructor(props, context) {
    super(props);
    this.state = {
      selectedContract: TestABI
    }
  }

  render() {
    console.log(this.props.contracts)
    return <div>
      Select...
      <FullContract contract={this.state.selectedContract} />
    </div>;
  }
}

export default ABIPlayGround;
